### ISSUE TITLE
Wypożyczanie - imię + nazwisko zamiast imię+pesel

### ISSUE THREAD

**Issue by piotrmaslanka** [piotrmaslanka/scrooge#27]
Bo nie będzie wiadomo kto co w końcu wypożyczył.

Zrobić żeby na liśćie było imię+nazwisko zamiast imię+pesel.

**Comment by piotrmaslanka** [comment]
To jest na stronie przedmiotu wypożyczonego.

**Comment by matulik** [comment]
Hehe
