### ISSUE TITLE
użytkownik bez praw admina nie ma możliwości wypożyczenia niczego bo nie może sie dostać do edycji majątku

### ISSUE THREAD

**Issue by ChaosPainter** [piotrmaslanka/scrooge#33]

**Comment by piotrmaslanka** [comment]
No to niech się może dostać, tylko niech nie zapisuje.

**Comment by ChaosPainter** [comment]
sprawdzajmy czy ma prawa dostępu na przyciskach tam gdzie nie powinien nic zmieniać

i może zmieńmy "edycja majątku" na "Majątek"

**Comment by matulik** [comment]
Już może.
