### ISSUE TITLE
Wyczyścić bazę z pierdół i dodać kilka sensownych pozycji

### ISSUE THREAD

**Issue by matulik** [piotrmaslanka/scrooge#37]

**Comment by ChaosPainter** [comment]
konta w bazie
login: admin pass: admin
login: user pass: user

**Comment by matulik** [comment]
Jeśli nie chcesz żeby Cie trafił piorun jasny siarczysty podczas dodawania majątku to zrób to przez bazę - powinno być szybciej :)

**Comment by piotrmaslanka** [comment]
Potwierdzam. To jest by design.

Serwer co prawda ma 350 Mbps DSL, ale to idzie po radiu, a dzisiaj zimno więc te fale takie zmarznięte idą powoli.

**Comment by matulik** [comment]
Zmieniłem imiona oraz nazwiska dla admina i usera.
